/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2024. All rights reserved.
 * Generated by the Cloud Object compiler. DO NOT EDIT!
 */
import type { CloudObjectLikely } from '../ImportObject';
type CloudEnvelope = {
    accessToken: string;
    payload: object;
};
type CloudResponse = {
    ok: boolean;
    data: object;
    message: string;
};

/**
 * Temporary isolated location object. checkLocation separates account-token and
 * coordinate validation from the Cloud DB query performed by listNearbyCards.
 */
export class ShikeLocation implements CloudObjectLikely {
    public name = 'shike-location';
    public async checkLocation(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listNearbyCards(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
}

