export { importObject } from './src/main/ets/ImportObject';
export { ShikeService } from './src/main/ets/shike-service/ShikeService';
export { ShikeMedia } from './src/main/ets/shike-media/ShikeMedia';

export interface CloudEnvelope {
  accessToken: string;
  payload: object;
}

export { ShikeLocation } from './src/main/ets/shike-location/ShikeLocation';
export { ShikeAuth } from './src/main/ets/shike-auth/ShikeAuth';
