/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2024. All rights reserved.
 * Generated by the Cloud Object compiler. DO NOT EDIT!
 */
import type { CloudObjectLikely } from '../ImportObject';
type CloudEnvelope = {
    accessToken: string;
    payload: object;
};
type CloudResponse = {
    ok: boolean;
    data: object;
    message: string;
    code?: string;
};

export class ShikeService implements CloudObjectLikely {
    public name = 'shike-service';
    public async getStage47Capabilities(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getTastePreference(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async updateTastePreference(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async clearTastePreference(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listPersonalizedRecommendations(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listFoodLists(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async createFoodList(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async updateFoodList(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async deleteFoodList(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listFoodListItems(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async addFoodListItem(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async removeFoodListItem(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async reorderFoodListItems(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getPersonalFoodState(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async updatePersonalFoodState(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getMealCandidates(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async createMealPoll(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getMealPoll(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async addMealPollOption(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async voteMealPoll(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async closeMealPoll(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async cancelMealPoll(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async stopMealPollOptions(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getUserPage(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listMerchantRankings(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }

    public async setCardReactionV2(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getDiscoveryCapabilities(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listMapMerchants(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async searchPublicCards(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getMerchantRecommendations(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getStage2Capabilities(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async resolveMerchant(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async createUserMerchant(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async updateUserMerchant(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getMerchant(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listModerationMerchants(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async moderateMerchant(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async reconcileMerchantCounters(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getCardEditContext(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getRevisionMedia(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async setCardReaction(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async submitCardRevision(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getCardRevision(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async withdrawCardRevision(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listModerationRevisions(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async moderateCardRevision(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async startMigrationJob(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async processMigrationJob(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getMigrationStatus(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listMaintenanceJobs(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getMaintenanceJob(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async retryMaintenanceJob(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async validateLifecycleJob(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }


    public async processFriendCleanupJob(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listModerationCards(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async moderateCard(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async completeLegacyLogin(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async startEmailBinding(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async completeEmailBinding(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async upsertProfile(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async prepareCardPhoto(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async uploadCardPhoto(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getPublicMedia(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async publishCard(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listNearbyCards(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listFriendRankings(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getFriendProfile(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getCardDetail(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listMyCards(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listMyFavoriteCards(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listReceivedComments(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async searchUsers(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listFriends(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async sendFriendRequest(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async respondFriendRequest(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async cancelFriendRequest(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async blockUser(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async unblockUser(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async reportUser(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async removeFriend(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listConversations(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listMessages(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async sendMessage(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async createGroupChat(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listGroupConversations(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getGroupChat(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listGroupMessages(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async sendGroupMessage(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async leaveGroupChat(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async removeGroupMember(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listNotifications(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async markNotificationRead(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async markAllNotificationsRead(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async openNotification(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async registerPushDevice(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async unregisterPushDevice(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async syncServiceCardForms(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async unregisterServiceCardForms(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async pushServiceCardUpdate(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async reportCard(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async toggleCardAction(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async createCardComment(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async deleteCardComment(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async toggleCommentReaction(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async deleteOwnCard(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async deleteAccountData(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
}

