/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2024. All rights reserved.
 * Generated by the Cloud Object compiler. DO NOT EDIT!
 */
import type { CloudObjectLikely } from '../ImportObject';
type CloudEnvelope = {
    accessToken: string;
    payload: object;
};
type CloudResponse = {
    ok: boolean;
    data: object;
    message: string;
};

export class ShikeService implements CloudObjectLikely {
    public name = 'shike-service';
    public async completeLegacyLogin(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async startEmailBinding(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async completeEmailBinding(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async upsertProfile(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async prepareCardPhoto(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async uploadCardPhoto(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getPublicMedia(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async publishCard(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listNearbyCards(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listFriendRankings(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getFriendProfile(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getCardDetail(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listMyCards(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listMyFavoriteCards(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listReceivedComments(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async searchUsers(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listFriends(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async sendFriendRequest(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async respondFriendRequest(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async cancelFriendRequest(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async blockUser(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async unblockUser(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async reportUser(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async removeFriend(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listConversations(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listMessages(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async sendMessage(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async createGroupChat(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listGroupConversations(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getGroupChat(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listGroupMessages(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async sendGroupMessage(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async leaveGroupChat(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async removeGroupMember(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async listNotifications(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async markNotificationRead(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async markAllNotificationsRead(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async openNotification(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async registerPushDevice(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async unregisterPushDevice(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async syncServiceCardForms(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async unregisterServiceCardForms(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async pushServiceCardUpdate(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async reportCard(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async toggleCardAction(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async createCardComment(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async deleteCardComment(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async toggleCommentReaction(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async deleteOwnCard(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async deleteAccountData(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
}
