/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2024. All rights reserved.
 * Generated by the Cloud Object compiler. DO NOT EDIT!
 */
import type { CloudObjectLikely } from '../ImportObject';
type CloudEnvelope = {
    accessToken: string;
    payload: object;
};
type CloudResponse = {
    ok: boolean;
    data: object;
    message: string;
};

export class ShikeAuth implements CloudObjectLikely {
    public name = 'shike-auth';
    public async exchangeHuaweiAccount(input: CloudEnvelope): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
}

