/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2024. All rights reserved.
 * Generated by the Cloud Object compiler. DO NOT EDIT!
 */
import type { CloudObjectLikely } from '../ImportObject';
type CloudResponse = {
    ok: boolean;
    data: object;
    message: string;
};

/**
 * Authenticated media boundary. Client methods validate the AGC access token
 * and the Cloud DB media record; execute remains for signed service-to-service
 * storage operations only.
 */
export class ShikeMedia implements CloudObjectLikely {
    public name = 'shike-media';
    public async prepareCardPhoto(input: object): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async uploadCardPhoto(input: object): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    public async getPublicMedia(input: object): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
    /** Internal only: shike-service supplies a HMAC-protected envelope. */
    public async execute(input: object): Promise<CloudResponse> {
        return Promise.reject(new Error('Method not implemented.'));
    }
}

